### ISSUE TITLE
Error running CO+Pt111.py

### ISSUE THREAD

**Issue by lopeztarifa** [SCM-NV/pyZacros#80]
Hi @nfaguirrec, 

I am trying to run the [CO+Pt111.py](https://github.com/SCM-NV/pyZacros/blob/master/examples/CO%2BPt111/CO%2BPt111.py), 
AMS version 2022.103, r104886 2022-06-17 and the distributed pyZacros version 1.0.0.

Then, I got the following error:

```
amspython CO+Pt111.py
[20.12|20:01:27] PLAMS working folder: /Users/plopez/Programs/ReaxPro/pyZacros/examples/CO+Pt111/plams_workdir
[20.12|20:01:27] JOB pes_exploration STARTED
[20.12|20:01:27] JOB pes_exploration RUNNING
[20.12|20:02:21] JOB pes_exploration FINISHED
[20.12|20:02:21] Job pes_exploration reported warnings. Please check the the output
[20.12|20:02:21] JOB pes_exploration SUCCESSFUL
All stationary points:
======================
State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
State 4: COPt36 transition state @ -7.62254756 Hartree (found 13 times, results on State-4_TS_2-3)
  +- Reactants: State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
     Products:  State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Prefactors: 1.586E+13:2.313E+12
State 5: COPt36 transition state @ -7.62243002 Hartree (found 3 times, results on State-5_TS_3-1)
  +- Reactants: State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Products:  State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
     Prefactors: 2.374E+12:1.652E+13
Fragment 1: CO local minimum @ -0.42445368 Hartree (results on Fragment-1)
Fragment 2: Pt36 local minimum @ -7.15428639 Hartree (results on Fragment-2)
FragmentedState 1: CO+Pt36 local minimum @ -7.57874007 Hartree (fragments [1, 2])
  +- State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
  |  Prefactors: 8.051E+06:1.667E+16
  +- State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
  |  Prefactors: 8.051E+06:1.642E+16
  +- State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Prefactors: 8.051E+06:2.395E+15
[20.12|20:02:22] JOB binding_sites STARTED
[20.12|20:02:22] JOB binding_sites RUNNING
[20.12|20:02:40] JOB binding_sites FINISHED
[20.12|20:02:40] JOB binding_sites SUCCESSFUL
Traceback (most recent call last):
  File "CO+Pt111.py", line 48, in <module>
    loader_ads.replace_site_types( ['A','B','C'], ['fcc','br','hcp'] )
    AttributeError: 'RKFLoader' object has no attribute 'replace_site_types'
```
It seems the method is not available anymore. Can you have a look?

Thanks, 
Pablo

**Comment by lopeztarifa** [comment]
Running with a newer pyZacros v.1.2 version crashes with a different error:

```
PLAMS working folder: /Users/plopez/Programs/ReaxPro/pyZacros/examples/CO+Pt111/plams_workdir
[05.01|13:16:38] JOB pes_exploration STARTED
[05.01|13:16:38] JOB pes_exploration RUNNING
[05.01|13:17:21] JOB pes_exploration FINISHED
[05.01|13:17:22] Job pes_exploration reported warnings. Please check the output
[05.01|13:17:22] Pickling of pes_exploration failed
[05.01|13:17:22] JOB pes_exploration SUCCESSFUL
All stationary points:
======================
State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
State 4: COPt36 transition state @ -7.62254756 Hartree (found 13 times, results on State-4_TS_2-3)
  +- Reactants: State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
     Products:  State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Prefactors: 1.586E+13:2.313E+12
State 5: COPt36 transition state @ -7.62243002 Hartree (found 3 times, results on State-5_TS_3-1)
  +- Reactants: State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Products:  State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
     Prefactors: 2.374E+12:1.652E+13
Fragment 1: CO local minimum @ -0.42445368 Hartree (results on Fragment-1)
Fragment 2: Pt36 local minimum @ -7.15428639 Hartree (results on Fragment-2)
FragmentedState 1: CO+Pt36 local minimum @ -7.57874007 Hartree (fragments [1, 2])
  +- State 1: COPt36 local minimum @ -7.65164229 Hartree (found 1 times, results on State-1_MIN)
  |  Prefactors: 8.051E+06:1.667E+16
  +- State 2: COPt36 local minimum @ -7.65157184 Hartree (found 1 times, results on State-2_MIN)
  |  Prefactors: 8.051E+06:1.642E+16
  +- State 3: COPt36 local minimum @ -7.62382116 Hartree (found 1 times, results on State-3_MIN)
     Prefactors: 8.051E+06:2.395E+15
[05.01|13:17:22] JOB binding_sites STARTED
[05.01|13:17:22] JOB binding_sites RUNNING
[05.01|13:17:39] JOB binding_sites FINISHED
[05.01|13:17:39] Pickling of binding_sites failed
[05.01|13:17:39] JOB binding_sites SUCCESSFUL
Traceback (most recent call last):
  File "/Users/plopez/Programs/miniconda3/envs/osp/lib/python3.9/site-packages/plams-1.5.1-py3.9.egg/scm/plams/tools/kftools.py", line 66, in read
    vtype, vlb, vstart, vlen = tmp[variable]
KeyError: 'referenceRegionLabel'
```

**Comment by nfaguirrec** [comment]
Hi @lopeztarifa ,

This example works for me with the current version of the pyZacros (master branch) and AMS. Maybe it is the AMS version. Are you executing this in the VM? If so, I can update AMS there.

Nestor

**Comment by lopeztarifa** [comment]
Hi @nfaguirrec, 

Thanks, it seems that there is a required AMS version in order to run the script. What is yours?
On my laptop, I am using the downloadable one, AMS version 2022.103, r104886 2022-06-17, that crashes (as shown above). 

In the VM I load the 
source /data/volume_1/Software/ams2022/amsbashrc.sh

That points out at the
/data/volume_1/Software/ams2022/bin

of AMS Version 2022.204 (?). 

Still is not enough to run it: 


```
Traceback (most recent call last):
  File "CO+Pt111.py", line 47, in <module>
    loader_ads = scm.pyzacros.RKFLoader( results_ads )
  File "/home/plopeztari/.scm/python/AMS2022.2.venv/lib/python3.8/site-packages/pyzacros-1.2.0-py3.8.egg/scm/pyzacros/core/RKFLoader.py", line 28, in __init__
    self.__deriveLatticeAndMechanism( results )
  File "/home/plopeztari/.scm/python/AMS2022.2.venv/lib/python3.8/site-packages/pyzacros-1.2.0-py3.8.egg/scm/pyzacros/core/RKFLoader.py", line 53, in __deriveLatticeAndMechanism
    latticeVectors = [ [latticeVectors[3*i+j]/angs for j in range(nLatticeVectors) ] for i in range(nLatticeVectors) ]
TypeError: 'NoneType' object cannot be interpreted as an integer
```

As you know we are short on hours at the VM, so you need to tell me when you have time to look at this :S then I will put the machine up again. Hopefully, the wallet will be renewed soon. 

cheers,
Pablo

**Comment by nfaguirrec** [comment]
The problem was because of the AMS license. I just updated it, and now the example works as expected.

Nestor

**Comment by lopeztarifa** [comment]
Hi @nfaguirrec, thanks! 

Would be possible to write at least on the head of the script the minimum version of AMS you need?

**Comment by lopeztarifa** [comment]
Thanks to @nfaguirrec the problem was solved by using the CO+Pt111.py example of the distributed version and deleting the virtual environments at the local folder:

~/home/user/.scm/python

Now the example rocks!
